### ISSUE TITLE
command 'cdnjs.search' not found

### ISSUE THREAD

**Issue by macjabeth** [Jakobud/vscode-cdnjs#4] opened 2017-03-06 20:50 UTC
When I try to use the plugin, I just get this error.

Using Ubuntu 16.04.

VSCode Info:
Version 1.10.1
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by Jakobud** [comment] 2017-03-06 21:14
You're the second person to report this issue. Do you have any other extensions installed?

**Comment by Jakobud** [comment] 2017-03-06 22:58
Duplicate of #1

**Closed as completed by Jakobud** 2017-03-06 22:58 UTC
